#include "constants.h"

const std::string APPLICATION_DESCRIPTION =
        "LinkDove - удобный и стильный мессенджер, позволяющий общаться людям "
        "со всех уголков планеты. Вы можете переписываться в чатах, группах и "
        "каналах, настраивать свой профиль и приложение. Вперед к новому общению!";

const std::string TEXT_MSG = "TEXT_MSG_TYPE";
const std::string AUDIO_MSG = "AUDIO_MSG_TYPE";
const std::string IMAGE_MSG = "IMAGE_MSG_TYPE";

const std::string LOGIN_REQUEST = "LOGIN";
const std::string LOGIN_SUCCESS = "LOGIN_SUCCESS";
const std::string LOGIN_FAILED  = "LOGIN_FAILED";
const std::string LOGIN_BANNED  = "LOGIN_BANNED";

const std::string REGISTER_REQUEST = "REGISTER";
const std::string REGISTER_SUCCESS = "REGISTER_SUCCESS";
const std::string REGISTER_FAILED  = "REGISTER_FAILED";

const std::string SEND_COMPLAINT_REQUEST = "SEND_COMPLAINT";
const std::string SEND_COMPLAINT_SUCCESS = "SEND_COMPLAINT_SUCCESS";
const std::string SEND_COMPLAINT_FAILED  = "SEND_COMPLAINT_FAILED";

const std::string DEL_COMPLAINT_REQUEST = "DEL_COMPLAINT";
const std::string DEL_COMPLAINT_SUCCESS = "DEL_COMPLAINT_SUCCESS";
const std::string DEL_COMPLAINT_FAILED  = "DEL_COMPLAINT_FAILED";

const std::string GET_COMPLAINTS_REQUEST = "GET_COMPLAINTS";
const std::string GET_COMPLAINTS_SUCCESS = "GET_COMPLAINTS_SUCCESS";
const std::string GET_COMPLAINTS_FAILED  = "GET_COMPLAINTS_FAILED";

const std::string UPDATE_USER_REQUEST = "UPDATE_USER";
const std::string UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const std::string UPDATE_USER_FAILED  = "UPDATE_USER_FAILED";

const std::string FIND_USER_REQUEST = "FIND_USER";
const std::string FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
const std::string FIND_USER_FAILED  = "FIND_USER_FAILED";

const std::string BAN_USER_REQUEST = "BAN_USER";
const std::string BAN_USER_SUCCESS = "BAN_USER_SUCCESS";
const std::string BAN_USER_FAILED  = "BAN_USER_FAILED";

const std::string SEND_MSG_REQUEST       = "SEND_MSG";
const std::string SEND_IND_MSG_SUCCESS   = "SEND_IND_MSG_SUCCESS";
const std::string SEND_IND_MSG_FAILED    = "SEND_IND_MSG_FAILED";
const std::string SEND_CHNNL_MSG_SUCCESS = "SEND_CHNNL_MSG_SUCCESS";
const std::string SEND_CHNNL_MSG_FAILED  = "SEND_CHNNL_MSG_FAILED";
const std::string SEND_CHAT_MSG_SUCCESS  = "SEND_CHAT_MSG_SUCCESS";
const std::string SEND_CHAT_MSG_FAILED   = "SEND_CHAT_MSG_FAILED";

const std::string GET_IND_MSG_REQUEST = "GET_IND_MSG";
const std::string GET_IND_MSG_SUCCESS = "GET_IND_MSG_SUCCESS";
const std::string GET_IND_MSG_FAILED  = "GET_IND_MSG_FAILED";

const std::string GET_INTERLOCUTORS_REQUEST = "GET_INTRLCTR";
const std::string GET_INTERLOCUTORS_SUCCESS = "GET_INTRLCTR_SUCCESS";
const std::string GET_INTERLOCUTORS_FAILED  = "GET_INTRLCTR_FAILED";

const std::string DELETE_IND_CHAT_REQUEST = "DEL_IND_CHAT";
const std::string DELETE_IND_CHAT_SUCCESS = "DEL_IND_CHAT_SUCCESS";
const std::string DELETE_IND_CHAT_FAILED  = "DEL_IND_CHAT_FAILED";

const std::string CREATE_CHANNEL_REQUEST = "CREATE_CHNNL";
const std::string CREATE_CHANNEL_SUCCESS = "CREATE_CHNNL_SUCCESS";
const std::string CREATE_CHANNEL_FAILED  = "CREATE_CHNNL_FAILED";

const std::string FIND_CHANNEL_REQUEST = "FIND_CHNNL";
const std::string FIND_CHANNEL_SUCCESS = "FIND_CHNNL_SUCCESS";
const std::string FIND_CHANNEL_FAILED  = "FIND_CHNNL_FAILED";

const std::string GET_CHANNELS_REQUEST = "GET_CHNNLS";
const std::string GET_CHANNELS_SUCCESS = "GET_CHNNLS_SUCCESS";
const std::string GET_CHANNELS_FAILED  = "GET_CHNNLS_FAILED";

const std::string IS_CHANNEL_PARTICIPANT_REQUEST = "IS_CHNNL_PRT";
const std::string IS_CHANNEL_PARTICIPANT_SUCCESS = "IS_CHNNL_PRT_SUCCESS";
const std::string IS_CHANNEL_PARTICIPANT_FAILED  = "IS_CHNNL_PRT_FAILED";

const std::string ADD_PARTICIPANT_TO_CHANNEL_REQUEST = "ADD_PRT_CHNNL";
const std::string ADD_PARTICIPANT_TO_CHANNEL_SUCCESS = "ADD_PRT_CHNNL_SUCCESS";
const std::string ADD_PARTICIPANT_TO_CHANNEL_FAILED  = "ADD_PRT_CHNNL_FAILED";

const std::string GET_CHNNL_MSG_REQUEST = "GET_CHNNL_MSG";
const std::string GET_CHNNL_MSG_SUCCESS = "GET_CHNNL_MSG_SUCCESS";
const std::string GET_CHNNL_MSG_FAILED  = "GET_CHNNL_MSG_FAILED";

const std::string GET_CHNNL_PARTICIPANTS_REQUEST = "GET_CHNNL_PRT";
const std::string GET_CHNNL_PARTICIPANTS_SUCCESS = "GET_CHNNL_PRT_SUCCESS";
const std::string GET_CHNNL_PARTICIPANTS_FAILED  = "GET_CHNNL_PRT_FAILED";

const std::string DELETE_CHANNEL_REQUEST = "DEL_CHANNEL";
const std::string DELETE_CHANNEL_SUCCESS = "DEL_CHANNEL_SUCCESS";
const std::string DELETE_CHANNEL_FAILED  = "DEL_CHANNEL_FAILED";

const std::string QUIT_CHANNEL_REQUEST = "QUIT_CHANNEL";
const std::string QUIT_CHANNEL_SUCCESS = "QUIT_CHANNEL_SUCCESS";
const std::string QUIT_CHANNEL_FAILED  = "QUIT_CHANNEL_FAILED";

const std::string REMOVE_USER_FROM_CHANNEL_REQUEST = "RMV_FROM_CHANNEL";
const std::string REMOVE_USER_FROM_CHANNEL_SUCCESS = "RMV_FROM_CHANNEL_SUCCESS";
const std::string REMOVE_USER_FROM_CHANNEL_FAILED  = "RMV_FROM_CHANNEL_FAILED";

const std::string CREATE_CHAT_REQUEST = "CREATE_CHAT";
const std::string CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
const std::string CREATE_CHAT_FAILED  = "CREATE_CHAT_FAILED";

const std::string GET_CHATS_REQUEST = "GET_CHATS";
const std::string GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
const std::string GET_CHATS_FAILED  = "GET_CHATS_FAILEDs";

const std::string FIND_CHAT_REQUEST = "FIND_CHAT";
const std::string FIND_CHAT_SUCCESS = "FIND_CHAT_SUCCESS";
const std::string FIND_CHAT_FAILED  = "FIND_CHAT_FAILED";

const std::string IS_CHAT_PARTICIPANT_REQUEST = "IS_CHAT_PRT";
const std::string IS_CHAT_PARTICIPANT_SUCCESS = "IS_CHAT_PRT_SUCCESS";
const std::string IS_CHAT_PARTICIPANT_FAILED  = "IS_CHAT_PRT_FAILED";

const std::string ADD_PARTICIPANT_TO_CHAT_REQUEST = "ADD_PRT_CHAT";
const std::string ADD_PARTICIPANT_TO_CHAT_SUCCESS = "ADD_PRT_CHAT_SUCCESS";
const std::string ADD_PARTICIPANT_TO_CHAT_FAILED  = "ADD_PRT_CHAT_FAILED";

const std::string GET_CHAT_MSG_REQUEST = "GET_CHAT_MSG";
const std::string GET_CHAT_MSG_SUCCESS = "GET_CHAT_MSG_SUCCESS";
const std::string GET_CHAT_MSG_FAILED  = "GET_CHAT_MSG_FAILED";

const std::string GET_CHAT_PARTICIPANTS_REQUEST = "GET_CHAT_PRT";
const std::string GET_CHAT_PARTICIPANTS_SUCCESS = "GET_CHAT_PRT_SUCCESS";
const std::string GET_CHAT_PARTICIPANTS_FAILED  = "GET_CHAT_PRT_FAILED";

const std::string DELETE_CHAT_REQUEST = "DEL_CHAT";
const std::string DELETE_CHAT_SUCCESS = "DEL_CHAT_SUCCESS";
const std::string DELETE_CHAT_FAILED  = "DEL_CHAT_FAILED";

const std::string QUIT_CHAT_REQUEST = "QUIT_CHAT";
const std::string QUIT_CHAT_SUCCESS = "QUIT_CHAT_SUCCESS";
const std::string QUIT_CHAT_FAILED  = "QUIT_CHAT_FAILED";

const std::string REMOVE_USER_FROM_CHAT_REQUEST = "RMV_FROM_CHAT";
const std::string REMOVE_USER_FROM_CHAT_SUCCESS = "RMV_FROM_CHAT_SUCCESS";
const std::string REMOVE_USER_FROM_CHAT_FAILED  = "RMV_FROM_CHAT_FAILED";

const std::string SEND_USER_ANSWER_REQUEST = "SEND_USER_ANSWER";
const std::string SEND_USER_ANSWER_SUCCESS = "SEND_USER_ANSWER_SUCCESS";
const std::string SEND_USER_ANSWER_FAILED  = "SEND_USER_ANSWER_FAILED";

const std::string GET_NOTIFICATIONS_REQUEST = "GET_NTFCS";
const std::string GET_NOTIFICATIONS_SUCCESS = "GET_NTFCS_SUCCESS";
const std::string GET_NOTIFICATIONS_FAILED  = "GET_NTFCS_FAILED";

const std::string DEL_NOTIFICATION_REQUEST = "DEL_NTFCS";
const std::string DEL_NOTIFICATION_SUCCESS = "DEL_NTFCS_SUCCESS";
const std::string DEL_NOTIFICATION_FAILED  = "DEL_NTFCS_FAILED";

const std::string DEL_MSG_REQUEST         = "DEL_MSG";
const std::string DEL_IND_MSG_SUCCESS     = "DEL_IND_MSG_SUCCESS";
const std::string DEL_IND_MSG_FAILED      = "DEL_IND_MSG_FAILED";
const std::string DEL_CHANNEL_MSG_SUCCESS = "DEL_CHNNL_MSG_SUCCESS";
const std::string DEL_CHANNEL_MSG_FAILED  = "DEL_CHNNL_MSG_FAILED";
const std::string DEL_CHAT_MSG_SUCCESS    = "DEL_CHAT_MSG_SUCCESS";
const std::string DEL_CHAT_MSG_FAILED     = "DEL_CHAT_MSG_FAILED";
