#include "constants.h"

const char *APPLICATION_DESCRIPTION =
        "LinkDove - удобный и стильный мессенджер, позволяющий общаться людям "
        "со всех уголков планеты. Вы можете переписываться в чатах, группах и "
        "каналах, настраивать свой профиль и приложение. Вперед к новому общению!";

const char *TEXT_MSG = "TEXT_MSG_TYPE";
const char *AUDIO_MSG = "AUDIO_MSG_TYPE";
const char *IMAGE_MSG = "IMAGE_MSG_TYPE";

const char *LOGIN_REQUEST = "LOGIN";
const char *LOGIN_SUCCESS = "LOGIN_SUCCESS";
const char *LOGIN_FAILED  = "LOGIN_FAILED";
const char *LOGIN_BANNED  = "LOGIN_BANNED";

const char *REGISTER_REQUEST = "REGISTER";
const char *REGISTER_SUCCESS = "REGISTER_SUCCESS";
const char *REGISTER_FAILED  = "REGISTER_FAILED";

const char *SEND_COMPLAINT_REQUEST = "SEND_COMPLAINT";
const char *SEND_COMPLAINT_SUCCESS = "SEND_COMPLAINT_SUCCESS";
const char *SEND_COMPLAINT_FAILED  = "SEND_COMPLAINT_FAILED";

const char *DEL_COMPLAINT_REQUEST = "DEL_COMPLAINT";
const char *DEL_COMPLAINT_SUCCESS = "DEL_COMPLAINT_SUCCESS";
const char *DEL_COMPLAINT_FAILED  = "DEL_COMPLAINT_FAILED";

const char *GET_COMPLAINTS_REQUEST = "GET_COMPLAINTS";
const char *GET_COMPLAINTS_SUCCESS = "GET_COMPLAINTS_SUCCESS";
const char *GET_COMPLAINTS_FAILED  = "GET_COMPLAINTS_FAILED";

const char *UPDATE_USER_REQUEST = "UPDATE_USER";
const char *UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const char *UPDATE_USER_FAILED  = "UPDATE_USER_FAILED";

const char *FIND_USER_REQUEST = "FIND_USER";
const char *FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
const char *FIND_USER_FAILED  = "FIND_USER_FAILED";

const char *BAN_USER_REQUEST = "BAN_USER";
const char *BAN_USER_SUCCESS = "BAN_USER_SUCCESS";
const char *BAN_USER_FAILED  = "BAN_USER_FAILED";

const char *SEND_MSG_REQUEST       = "SEND_MSG";
const char *SEND_IND_MSG_SUCCESS   = "SEND_IND_MSG_SUCCESS";
const char *SEND_IND_MSG_FAILED    = "SEND_IND_MSG_FAILED";
const char *SEND_CHNNL_MSG_SUCCESS = "SEND_CHNNL_MSG_SUCCESS";
const char *SEND_CHNNL_MSG_FAILED  = "SEND_CHNNL_MSG_FAILED";
const char *SEND_CHAT_MSG_SUCCESS  = "SEND_CHAT_MSG_SUCCESS";
const char *SEND_CHAT_MSG_FAILED   = "SEND_CHAT_MSG_FAILED";

const char *GET_IND_MSG_REQUEST = "GET_IND_MSG";
const char *GET_IND_MSG_SUCCESS = "GET_IND_MSG_SUCCESS";
const char *GET_IND_MSG_FAILED  = "GET_IND_MSG_FAILED";

const char *GET_INTERLOCUTORS_REQUEST = "GET_INTRLCTR";
const char *GET_INTERLOCUTORS_SUCCESS = "GET_INTRLCTR_SUCCESS";
const char *GET_INTERLOCUTORS_FAILED  = "GET_INTRLCTR_FAILED";

const char *CREATE_CHANNEL_REQUEST = "CREATE_CHNNL";
const char *CREATE_CHANNEL_SUCCESS = "CREATE_CHNNL_SUCCESS";
const char *CREATE_CHANNEL_FAILED  = "CREATE_CHNNL_FAILED";

const char *FIND_CHANNEL_REQUEST = "FIND_CHNNL";
const char *FIND_CHANNEL_SUCCESS = "FIND_CHNNL_SUCCESS";
const char *FIND_CHANNEL_FAILED  = "FIND_CHNNL_FAILED";

const char *GET_CHANNELS_REQUEST = "GET_CHNNLS";
const char *GET_CHANNELS_SUCCESS = "GET_CHNNLS_SUCCESS";
const char *GET_CHANNELS_FAILED  = "GET_CHNNLS_FAILED";

const char *IS_CHANNEL_PARTICIPANT_REQUEST = "IS_CHNNL_PRT";
const char *IS_CHANNEL_PARTICIPANT_SUCCESS = "IS_CHNNL_PRT_SUCCESS";
const char *IS_CHANNEL_PARTICIPANT_FAILED  = "IS_CHNNL_PRT_FAILED";

const char *ADD_PARTICIPANT_TO_CHANNEL_REQUEST = "ADD_PRT_CHNNL";
const char *ADD_PARTICIPANT_TO_CHANNEL_SUCCESS = "ADD_PRT_CHNNL_SUCCESS";
const char *ADD_PARTICIPANT_TO_CHANNEL_FAILED  = "ADD_PRT_CHNNL_FAILED";

const char *GET_CHNNL_MSG_REQUEST = "GET_CHNNL_MSG";
const char *GET_CHNNL_MSG_SUCCESS = "GET_CHNNL_MSG_SUCCESS";
const char *GET_CHNNL_MSG_FAILED  = "GET_CHNNL_MSG_FAILED";

const char *DELETE_CHANNEL_REQUEST = "DEL_CHANNEL";
const char *DELETE_CHANNEL_SUCCESS = "DEL_CHANNEL_SUCCESS";
const char *DELETE_CHANNEL_FAILED  = "DEL_CHANNEL_FAILED";

const char *CREATE_CHAT_REQUEST = "CREATE_CHAT";
const char *CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
const char *CREATE_CHAT_FAILED  = "CREATE_CHAT_FAILED";

const char *GET_CHATS_REQUEST = "GET_CHATS";
const char *GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
const char *GET_CHATS_FAILED  = "GET_CHATS_FAILEDs";

const char *FIND_CHAT_REQUEST = "FIND_CHAT";
const char *FIND_CHAT_SUCCESS = "FIND_CHAT_SUCCESS";
const char *FIND_CHAT_FAILED  = "FIND_CHAT_FAILED";

const char *IS_CHAT_PARTICIPANT_REQUEST = "IS_CHAT_PRT";
const char *IS_CHAT_PARTICIPANT_SUCCESS = "IS_CHAT_PRT_SUCCESS";
const char *IS_CHAT_PARTICIPANT_FAILED  = "IS_CHAT_PRT_FAILED";

const char *ADD_PARTICIPANT_TO_CHAT_REQUEST = "ADD_PRT_CHAT";
const char *ADD_PARTICIPANT_TO_CHAT_SUCCESS = "ADD_PRT_CHAT_SUCCESS";
const char *ADD_PARTICIPANT_TO_CHAT_FAILED  = "ADD_PRT_CHAT_FAILED";

const char *GET_CHAT_MSG_REQUEST = "GET_CHAT_MSG";
const char *GET_CHAT_MSG_SUCCESS = "GET_CHAT_MSG_SUCCESS";
const char *GET_CHAT_MSG_FAILED  = "GET_CHAT_MSG_FAILED";

const char *DELETE_CHAT_REQUEST = "DEL_CHAT";
const char *DELETE_CHAT_SUCCESS = "DEL_CHAT_SUCCESS";
const char *DELETE_CHAT_FAILED  = "DEL_CHAT_FAILED";
